image: gradle:7.2
variables:
    BUILD_NUMBER: $CI_PIPELINE_IID
    BRANCH_NAME: $CI_COMMIT_REF_NAME
    COMMIT_HASH: $CI_COMMIT_SHA
stages:
  - build
  - run-tests
  - process-coverage
  - process-coverage-api

build:
  stage: build
  script:
    - ./gradlew build
    - ./gradlew createArtifact
  artifacts:
    name: "${BRANCH_NAME}-${BUILD_NUMBER}-${COMMIT_HASH}"
    paths:
    - ./*/build/libs/*.jar
    - ./client/**/*


run-tests:
  stage: run-tests
  before_script:
    - echo "Clearing cache"
    - rm -rf $CI_PROJECT_DIR/.gradle/caches/
    - rm -rf $CI_PROJECT_DIR/.gradle/wrapper/
  script:
    - ./gradlew build
    - ./gradlew test


process-coverage:
  stage: process-coverage
  script:
    - rm -rf $CI_PROJECT_DIR/.gradle/caches/
    - rm -rf $CI_PROJECT_DIR/.gradle/wrapper/
    - ./gradlew build JacocoCoverageVerification
    - ./gradlew test
    - ./gradlew jacocoTestReport
    - cat domain/build/reports/jacoco/test/html/index.html

  coverage: '/Total.*?([0-9]{1,3})%/'




